#!/usr/bin/env python3

import argparse
import os
from datetime import datetime

cstr = argparse.ArgumentParser()
cstr.add_argument("--version", "-V", action="version",
                  help="version", version='v0.14 (c) Dmitriy Shishkovets,  EPAM, 2020')
cstr.add_argument("--lp", action="store_true", help="List files from parent dir")
cstr.add_argument("--lr", action="store_true", help="List files recursively")
cstr.add_argument("--ext", action="store_true", help="Filter by extension")
cstr.add_argument("--sn", action="store_true", help="Order out files by name")
cstr.add_argument("--sd", action="store_true", help="Order out files by creation date")
args = cstr.parse_args()

if args.lp:
    print("listed parrent")
if args.lr:
    print("Listed recurs")
if args.ext:
    print("filter by extension")
if args.sn:
    print("name sort")
if args.sd:
    print("date sort")

# output files only from the parent directory
basepath = '.'
for entry in os.listdir(basepath):
    if os.path.isfile(os.path.join(basepath, entry)):
        print(1, entry)

# list files recursively
def list_files(path):
    with os.scandir(path) as entries:
        for entry in entries:
            if entry.is_file():
                print(entry.name)
            elif entry.is_dir():
                list_files(entry.path)
#list_files('.')



# filter by file extension
for file_name in os.listdir('.'):
    if file_name.endswith('.py'):
        print(3, file_name)

# order output by filename
mylist = []

